### ISSUE TITLE
App Fails to Start

### ISSUE THREAD

**Issue by jennyhong** [ohtap/subcorpora-tool#35]
Hi there, I'm not familiar with node and am just trying to run the app based on the instructions in `README.md`. I'm getting these results:

```
npm run start

> ohtap-winnow@0.1.0 start /Users/jenny/Dropbox/code/subcorpora-tool
> node index.js

OHTAP Subcorpora Tool launched at localhost:5000

Initializing data from session.json...
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at initializeData (/Users/jenny/Dropbox/code/subcorpora-tool/index.js:43:15)
    at Server.<anonymous> (/Users/jenny/Dropbox/code/subcorpora-tool/index.js:83:3)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:210:5)
    at emitListeningNT (net.js:1334:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ohtap-winnow@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ohtap-winnow@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jenny/.npm/_logs/2019-11-05T03_30_26_657Z-debug.log
```

```
cat /Users/jenny/.npm/_logs/2019-11-05T03_30_26_657Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ohtap-winnow@0.1.0~prestart: ohtap-winnow@0.1.0
6 info lifecycle ohtap-winnow@0.1.0~start: ohtap-winnow@0.1.0
7 verbose lifecycle ohtap-winnow@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle ohtap-winnow@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jenny/Dropbox/code/subcorpora-tool/node_modules/.bin:/Users/jenny/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
9 verbose lifecycle ohtap-winnow@0.1.0~start: CWD: /Users/jenny/Dropbox/code/subcorpora-tool
10 silly lifecycle ohtap-winnow@0.1.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle ohtap-winnow@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle ohtap-winnow@0.1.0~start: Failed to exec start script
13 verbose stack Error: ohtap-winnow@0.1.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid ohtap-winnow@0.1.0
15 verbose cwd /Users/jenny/Dropbox/code/subcorpora-tool
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.12.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error ohtap-winnow@0.1.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the ohtap-winnow@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

And the `data/session.json` file is empty.

**Comment by hsun083** [comment]
Issue was that session.json file was being read from before its creation (async function). Fix: changed read in to synchronous function.
