### ISSUE TITLE
Adding a new collection fails

### ISSUE THREAD

**Issue by njmarine** [ohtap/subcorpora-tool#39]
```
Adding collection SHSF
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir './data/metadata-files/corpus-files/SHSF/'
    at Object.mkdirSync (fs.js:839:3)
    at DiskStorage.destination [as getDestination] (/Users/njmarine/Desktop/subcorpora-tool-master/index.js:107:12)
    at DiskStorage._handleFile (/Users/njmarine/Desktop/subcorpora-tool-master/node_modules/multer/storage/disk.js:31:8)
    at /Users/njmarine/Desktop/subcorpora-tool-master/node_modules/multer/lib/make-middleware.js:144:17
    at allowAll (/Users/njmarine/Desktop/subcorpora-tool-master/node_modules/multer/index.js:8:3)
    at wrappedFileFilter (/Users/njmarine/Desktop/subcorpora-tool-master/node_modules/multer/index.js:44:7)
    at Busboy.<anonymous> (/Users/njmarine/Desktop/subcorpora-tool-master/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (events.js:210:5)
    at Busboy.emit (/Users/njmarine/Desktop/subcorpora-tool-master/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/Users/njmarine/Desktop/subcorpora-tool-master/node_modules/busboy/lib/types/multipart.js:213:13) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: './data/metadata-files/corpus-files/SHSF/'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ohtap-winnow@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ohtap-winnow@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/njmarine/.npm/_logs/2019-11-21T19_36_42_181Z-debug.log
```

We had to manually run ` mkdir './data/metadata-files/corpus-files/SHSF/'`

**Comment by hsun083** [comment]
Issue: `dest` variable was wrong (was uploading into the metadata folder instead of collections).
